### ISSUE TITLE
Autocomplete for .NET 4.5.2...

### ISSUE THREAD

**Issue by cgm-wmaisenhelder** [VPKSoft/Scintilla.NET#26]
I am upgrading a .NET 4.5.2 project from the old CodePlex Scintilla.NET v2.5.2 to VPKSoft ScintillaNET v5.3.1.3.  I've got everything working except the autocomplete.  The main problem that I'm running in to is that the old component had and AutoCompleteList property, and I can't find a corresponding property on the new component.

Looking at your wiki, I saw the link to the AutoCompleteMenu-ScintillaNET project.  However, when I tried to install that package, I found that it only supports .NET 4.6.1.

Is there an autocomplete solution that I can use for .NET 4.5.2?

**Comment by VPKSoft** [comment]
Hi,
I'm not quite sure what auto complete menu do you mean? Is this [AutoCompleteMenu-ScintillaNET](https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET) the one you mean? I haven't worked with the CodePlex-series of the ScintillaNET. Just trying to keep this project originally by @jacobslusser alive.

**Comment by cgm-wmaisenhelder** [comment]
Hi,

Yes, that is the autocomplete that I meant.  The v2.5.2 version evidently had the menu built in.  I looked at the project that you referenced, but it only supports .NET 4.6.1.  I was just wondering if anyone was aware of an existing solution for .NET 4.5.2.

**Comment by VPKSoft** [comment]
Hi, I can create a PR for the [AutoCompleteMenu-ScintillaNET](https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET), with net45, Core, .NET 5 and .NET6 support. I doubt that the process is going to be slow. And of course I have to get started with that in the ongoing decade.

**Comment by cgm-wmaisenhelder** [comment]
Thanks! That would be awesome.

As an aside, I figured I would install earlier versions of [AutoCompleteMenu-ScintillaNET] (https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET) to see if I could find a .NET v4.5.2 one.  I actually got AutoCompleteMenu-ScintillaNET v1.6.1 to install, but then I started getting version conflicts for ScintillaNET between v3.6.3 and the latest version.

**Comment by VPKSoft** [comment]
Hi,
Here is the PR: https://github.com/Ahmad45123/AutoCompleteMenu-ScintillaNET/pull/10 and the NuGet package in an [alpha release](https://github.com/VPKSoft/AutoCompleteMenu-ScintillaNET/releases/tag/v.5.3.1-alpha) for manual download.
I don't know if the PR is ever going to be accepted and merged but it is done in either case.

**Comment by VPKSoft** [comment]
The pull request is complete - the rest (release process) is up to the author.
