### ISSUE TITLE
TextLength doesnt return valid result

### ISSUE THREAD

**Issue by Samkob** [VPKSoft/Scintilla.NET#45]
**Describe the bug**
For some reason, TextLength is not reporting a valid result. I set Text property with a string consisting of 95 characters, and yet, TextLength reports 158!

**To Reproduce**
var s = "MyProductName5 version 1.2.0.0\r\n© 2022 Name of   Developer, myemailher@yahoo.com\r\n\r\ninput 1 >\r\n";
this.Text = s;
var n1 = s.Length; // 95
var n2 = this.TextLength; // 158

**Expected behavior**
TextLength should have reported 158 given the string passed.

**Desktop (please complete the following information):**
 - OS: Windows 11 running on 64-bit

**Comment by VPKSoft** [comment]
Hi,
I'm having trouble reproducing this:
The code:
```cs
    private void mnuTestMethod_Click(object sender, EventArgs e)
    {
        var s = "MyProductName5 version 1.2.0.0\r\n© 2022 Name of Developer, myemailher@yahoo.com\r\n\r\ninput 1 >\r\n";
        scintilla.Text = s;
        MessageBox.Show($"{scintilla.TextLength} / {s.Length}");
    }
```

The result:
![image](https://user-images.githubusercontent.com/40712699/213522549-c9cf9b44-cb76-4e61-bcc3-b6ad221d266f.png)

**Comment by Samkob** [comment]
Thanks for the quick response. This is quite strange - I simply ran the demo app, and but I still get results below.
![image1](https://user-images.githubusercontent.com/123102681/213535390-215f9e18-b6fe-47ca-97fd-d294f670723c.png)

**Comment by Samkob** [comment]
I downloaded the source code again, and tried it once more, still TextLength returning strange results. Any ideas?
![image2](https://user-images.githubusercontent.com/123102681/213538055-70c36eb0-c701-41f3-aaa1-0707b8142fd8.png)

**Comment by VPKSoft** [comment]
The control needs to render == draw it self before the *TextLength* property works as expected. This is why it doesn't work in the form's constructor. The behaviour is due the underlying native Scintilla control. Make a button, etc. and run the test code from there.

**Comment by Samkob** [comment]
After allowing control to draw completely, properties works fine - thanks for your help.

**Comment by VPKSoft** [comment]
Okay, nice 👍
