### ISSUE TITLE
NullPointerException when running from SingleFile executable

### ISSUE THREAD

**Issue by jas88** [VPKSoft/Scintilla.NET#63]
https://github.com/VPKSoft/Scintilla.NET/blob/2e458d140067a9167e3c30e3c8e7a9ab0a9cb163/Shared/Scintilla.cs#L48 - this assumes GetExecutingAssembly().Location is not null, which isn't always true. Using 'AppDomain.CurrentDomain.BaseDirectory' instead (or as a fallback if attached to the existing approach for other cases?) would avoid this.

**Comment by VPKSoft** [comment]
Hi,
Thanks for pointing this out - has this null reference exception happened to you?

**Comment by jas88** [comment]
Yes - I'm just updating an application which uses Scintilla to use your package, and hit this as soon as I load the compiled .exe. As a temporary workaround I've used a LibHarmony patch to replace the whole `LocateNativeDllDirectory` method as above.

**Comment by VPKSoft** [comment]
Okay, then it is more urgent - I'll try to find the time to fix this in the coming weekend 👍

**Comment by VPKSoft** [comment]
This should be fixed now.
