### ISSUE TITLE
How do I set the encoding of Scintilla.NET

### ISSUE THREAD

**Issue by Z-orz** [VPKSoft/Scintilla.NET#70]
How do I set the encoding of Scintilla.NET

**Comment by VPKSoft** [comment]
Hi,
The encoding is always UTF8: https://github.com/VPKSoft/Scintilla.NET/blob/master/Shared/Scintilla.cs#L4425.
If you wish to load text other than UTF8, e.g. from a file see:  [File.ReadAllText](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?view=net-7.0#system-io-file-readalltext(system-string-system-text-encoding)).

**Comment by Z-orz** [comment]
OK, Thank you for your help.
