### ISSUE TITLE
CSS files visualization problem

### ISSUE THREAD

**Issue by lgaudouen** [VPKSoft/Scintilla.NET#71]
After days of unsuccessful attempts to use the VPK package Scintilla.NET for CSS files, I found the VPK project ScintillaLexers-v.1.1.15 which was to bring me the solution to the configuration of Scintilla and the Css lexer (with in addition the recovery of Notepad++ parameters).
Unfortunately, the display of a css file by TestLexer is incorrect (see image).
Would you have the solution?

![cssIssue](https://github.com/VPKSoft/Scintilla.NET/assets/5849176/ee01074e-f9d7-4914-b981-4dd8738f752f)

**Comment by VPKSoft** [comment]
Hi,
I don't have a direct solution for that issue which seems to draw the white-space in black background but I'll take a look. Also this is not Scintilla.NET issue so closing this here.

**Comment by lgaudouen** [comment]
There are not only white-spaces but also EoLs.
Also, not all whitespaces are displayed as black characters.
You say it's not a Scintilla.NET problem, so you think it's a scintilla-lexilla problem.
However, SciTE does not present the same problem and integrates the same source of the CSS lexer. By replacing the scintilla and lexilla dlls for Scintilla.NET with the latest versions (lexilla: 5.2.6 and scintilla: 5.3.6, also used by Nodepad++), I still have the same problem with Scintilla.Net.
